#集群版eureka配置
server:
  port: 7030
eureka:
  instance:
    hostname: eureka7030
  client:
    register-with-eureka: false # 表示不向注册中心注册自己
    fetch-registry: false #表示自己就是注册中心，负责维护服务，不需要检索服务
    service-url:
      defaultZone: http://eureka7010:7010/eureka/,http://eureka7020:7020/eureka/ #设置eureka的注册和查询地址